In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_excel('data_v5.xlsx')

In [4]:
ban_tweet = pd.read_excel('dengue_bangla.xlsx')
eng_tweet = pd.read_excel('english_tweets.xlsx')

In [5]:
ban_tweet = ban_tweet[['datetime','location']]
eng_tweet = eng_tweet[['datetime','location']]

In [10]:
data.head(20)

,locations_month,maxtempC,mintempC,avgtempC,sunHour,uvIndex,humidity,visibility,visibilityMiles,pressure,...,cloudcover,HeatIndexC,DewPointC,WindChillC,FeelsLikeC,rainFall,rainDays,date,locations,label
0,barisal2015-1,26.0,17.0,21.0,8.70,6.0,53.0,10.0,6.0,1015.0,...,1.5,24.0,13.0,23.0,23.0,10.17,3.0,2015-1,barisal,0
1,barisal2015-2,28.0,19.0,23.0,8.70,6.0,55.5,10.0,6.0,1013.5,...,9.5,26.0,14.0,25.0,26.0,2.26,3.0,2015-,barisal,0
2,barisal2015-3,33.0,22.0,27.0,11.60,7.0,50.5,10.0,6.0,1011.0,...,13.0,30.0,16.0,29.0,30.0,4.83,14.0,2015-3,barisal,0
3,barisal2015-4,33.0,26.5,29.0,12.75,7.0,67.5,10.0,6.0,1008.0,...,31.5,34.0,23.0,30.0,34.0,44.09,16.0,2015-4,barisal,0
4,barisal2015-5,35.0,28.0,31.0,13.10,8.0,69.5,10.0,6.0,1005.0,...,37.5,38.0,25.0,32.0,38.0,20.35,15.0,2015-5,barisal,0
5,barisal2015-6,33.0,29.0,31.0,12.00,8.0,70.0,10.0,6.0,1002.0,...,45.5,37.0,25.0,31.0,37.0,29.66,18.0,2015-6,barisal,0
6,barisal2015-7,32.0,27.5,29.5,12.00,7.0,77.0,10.0,6.0,999.0,...,57.5,35.0,25.0,30.0,35.0,68.01,26.0,2015-7,barisal,0
7,barisal2015-8,32.0,28.0,30.0,12.85,7.0,77.0,10.0,6.0,1003.0,...,45.5,36.0,25.0,30.0,36.0,38.65,21.0,2015-8,barisal,0
8,barisal2015-9,32.0,27.0,29.0,11.85,7.0,76.0,10.0,6.0,1005.0,...,38.5,35.0,25.0,30.0,35.0,80.97,24.0,2015-9,barisal,0
9,barisal2015-10,31.0,24.0,27.0,11.60,7.0,74.5,10.0,6.0,1010.5,...,26.0,32.0,24.0,29.0,32.0,36.15,18.0,2015-10,barisal,0
10,barisal2015-11,29.0,21.0,24.0,8.70,6.0,65.0,10.0,6.0,1013.0,...,1.0,29.0,20.0,27.0,29.0,3.09,4.0,2015-11,barisal,0
11,barisal2015-12,26.0,19.0,21.5,8.70,6.0,61.0,10.0,6.0,1015.0,...,14.0,25.0,15.5,23.0,24.0,9.67,8.0,2015-1,barisal,0
12,barisal2016-1,26.0,17.0,21.0,8.70,6.0,53.0,10.0,6.0,1015.0,...,2.0,25.0,13.0,23.0,23.5,0.64,2.0,2016-1,barisal,0
13,barisal2016-2,30.0,21.5,25.5,8.70,6.5,57.5,10.0,6.0,1014.0,...,9.0,28.5,18.0,27.0,28.5,7.40,5.0,2016-,barisal,0
14,barisal2016-3,34.0,25.0,29.0,11.60,7.0,54.0,10.0,6.0,1011.0,...,10.5,32.0,19.0,30.0,32.0,9.57,8.0,2016-3,barisal,0
15,barisal2016-4,35.0,27.0,30.5,12.70,8.0,68.0,10.0,6.0,1006.5,...,38.0,36.0,24.0,31.0,36.0,13.23,11.0,2016-4,barisal,0
16,barisal2016-5,34.5,28.0,31.0,13.10,8.0,70.5,10.0,6.0,1004.0,...,29.0,38.0,25.0,31.0,38.0,30.49,19.0,2016-5,barisal,0
17,barisal2016-6,33.0,28.0,30.0,13.30,7.5,75.0,10.0,6.0,1003.0,...,34.0,37.0,25.0,30.0,37.0,76.37,22.0,2016-6,barisal,0
18,barisal2016-7,33.0,27.0,30.0,13.10,6.0,78.0,9.0,5.0,1000.0,...,54.5,36.0,25.0,30.0,36.0,58.77,28.0,2016-7,barisal,0
19,barisal2016-8,33.0,27.0,29.0,12.80,7.0,77.0,10.0,6.0,1002.0,...,36.5,36.0,25.0,30.0,36.0,57.96,22.0,2016-8,barisal,0

In [12]:
data.set_index('locations_month',inplace=True)
data['date'] = ['20'+data.index[i].split('20')[1] for i in range(len(data))]

In [13]:
data

,maxtempC,mintempC,avgtempC,sunHour,uvIndex,humidity,visibility,visibilityMiles,pressure,pressureInches,cloudcover,HeatIndexC,DewPointC,WindChillC,FeelsLikeC,rainFall,rainDays,date,locations,label
locations_month,,,,,,,,,,,,,,,,,,,,
barisal2015-1,26.0,17.0,21.0,8.70,6.0,53.0,10.0,6.0,1015.0,30.0,1.5,24.0,13.0,23.0,23.0,10.17,3.0,2015-1,barisal,0
barisal2015-2,28.0,19.0,23.0,8.70,6.0,55.5,10.0,6.0,1013.5,30.0,9.5,26.0,14.0,25.0,26.0,2.26,3.0,2015-2,barisal,0
barisal2015-3,33.0,22.0,27.0,11.60,7.0,50.5,10.0,6.0,1011.0,30.0,13.0,30.0,16.0,29.0,30.0,4.83,14.0,2015-3,barisal,0
barisal2015-4,33.0,26.5,29.0,12.75,7.0,67.5,10.0,6.0,1008.0,30.0,31.5,34.0,23.0,30.0,34.0,44.09,16.0,2015-4,barisal,0
barisal2015-5,35.0,28.0,31.0,13.10,8.0,69.5,10.0,6.0,1005.0,30.0,37.5,38.0,25.0,32.0,38.0,20.35,15.0,2015-5,barisal,0
barisal2015-6,33.0,29.0,31.0,12.00,8.0,70.0,10.0,6.0,1002.0,30.0,45.5,37.0,25.0,31.0,37.0,29.66,18.0,2015-6,barisal,0
barisal2015-7,32.0,27.5,29.5,12.00,7.0,77.0,10.0,6.0,999.0,30.0,57.5,35.0,25.0,30.0,35.0,68.01,26.0,2015-7,barisal,0
barisal2015-8,32.0,28.0,30.0,12.85,7.0,77.0,10.0,6.0,1003.0,30.0,45.5,36.0,25.0,30.0,36.0,38.65,21.0,2015-8,barisal,0
barisal2015-9,32.0,27.0,29.0,11.85,7.0,76.0,10.0,6.0,1005.0,30.0,38.5,35.0,25.0,30.0,35.0,80.97,24.0,2015-9,barisal,0
barisal2015-10,31.0,24.0,27.0,11.60,7.0,74.5,10.0,6.0,1010.5,30.0,26.0,32.0,24.0,29.0,32.0,36.15,18.0,2015-10,barisal,0
barisal2015-11,29.0,21.0,24.0,8.70,6.0,65.0,10.0,6.0,1013.0,30.0,1.0,29.0,20.0,27.0,29.0,3.09,4.0,2015-11,barisal,0
barisal2015-12,26.0,19.0,21.5,8.70,6.0,61.0,10.0,6.0,1015.0,30.0,14.0,25.0,15.5,23.0,24.0,9.67,8.0,2015-12,barisal,0
barisal2016-1,26.0,17.0,21.0,8.70,6.0,53.0,10.0,6.0,1015.0,30.0,2.0,25.0,13.0,23.0,23.5,0.64,2.0,2016-1,barisal,0
barisal2016-2,30.0,21.5,25.5,8.70,6.5,57.5,10.0,6.0,1014.0,30.0,9.0,28.5,18.0,27.0,28.5,7.40,5.0,2016-2,barisal,0
barisal2016-3,34.0,25.0,29.0,11.60,7.0,54.0,10.0,6.0,1011.0,30.0,10.5,32.0,19.0,30.0,32.0,9.57,8.0,2016-3,barisal,0
barisal2016-4,35.0,27.0,30.5,12.70,8.0,68.0,10.0,6.0,1006.5,30.0,38.0,36.0,24.0,31.0,36.0,13.23,11.0,2016-4,barisal,0
barisal2016-5,34.5,28.0,31.0,13.10,8.0,70.5,10.0,6.0,1004.0,30.0,29.0,38.0,25.0,31.0,38.0,30.49,19.0,2016-5,barisal,0
barisal2016-6,33.0,28.0,30.0,13.30,7.5,75.0,10.0,6.0,1003.0,30.0,34.0,37.0,25.0,30.0,37.0,76.37,22.0,2016-6,barisal,0
barisal2016-7,33.0,27.0,30.0,13.10,6.0,78.0,9.0,5.0,1000.0,30.0,54.5,36.0,25.0,30.0,36.0,58.77,28.0,2016-7,barisal,0
barisal2016-8,33.0,27.0,29.0,12.80,7.0,77.0,10.0,6.0,1002.0,30.0,36.5,36.0,25.0,30.0,36.0,57.96,22.0,2016-8,barisal,0
barisal2016-9,32.0,27.0,29.0,11.60,7.0,78.5,10.0,5.0,1005.0,30.0,34.0,36.0,25.0,30.0,36.0,61.99,23.0,2016-9,barisal,0
barisal2016-10,31.0,25.0,27.5,11.60,7.0,76.5,10.0,6.0,1007.0,30.0,21.0,34.0,25.0,29.0,34.0,20.45,14.0,2016-10,barisal,0
barisal2016-11,28.0,19.5,23.0,8.70,6.0,67.5,10.0,6.0,1012.0,30.0,2.0,28.0,20.0,26.0,28.0,19.37,4.0,2016-11,barisal,0
barisal2016-12,27.0,17.0,22.0,8.70,6.0,59.5,10.0,6.0,1014.0,30.0,0.0,26.0,16.0,25.0,25.0,0.00,0.0,2016-12,barisal,0
barisal2017-1,27.0,16.0,21.0,8.70,6.0,47.0,10.0,6.0,1015.0,30.0,0.0,24.0,11.0,23.0,23.0,0.00,0.0,2017-1,barisal,0
barisal2017-2,30.0,19.0,24.0,8.70,6.0,46.5,10.0,6.0,1013.0,30.0,1.0,27.0,13.0,26.0,27.0,1.25,1.0,2017-2,barisal,0
barisal2017-3,31.0,21.5,26.0,11.60,7.0,66.5,10.0,6.0,1010.0,30.0,14.5,29.0,19.5,27.0,29.0,8.43,9.0,2017-3,barisal,0
barisal2017-4,33.5,26.0,29.0,11.90,7.0,74.0,10.0,6.0,1008.0,30.0,40.5,34.0,24.0,29.5,34.0,8.06,7.0,2017-4,barisal,0
barisal2017-5,36.0,28.0,31.0,13.10,8.0,68.5,10.0,6.0,1004.0,30.0,24.5,38.5,25.0,32.0,38.5,17.34,11.0,2017-5,barisal,0
barisal2017-6,33.0,28.0,30.0,13.30,7.0,77.0,10.0,6.0,1001.0,30.0,36.5,37.0,25.0,30.0,37.0,59.52,21.0,2017-6,barisal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sylhet2017-4,32.0,23.0,27.0,11.95,6.0,85.5,8.0,4.0,1009.0,30.0,40.5,30.0,23.0,27.0,30.0,256.14,20.0,2017-4,sylhet,0
sylhet2017-5,34.0,25.0,28.5,13.20,7.0,76.0,10.0,6.0,1006.0,30.0,17.0,34.0,24.0,29.5,34.0,109.26,21.0,2017-5,sylhet,0
sylhet2017-6,33.0,25.0,28.0,13.35,6.5,86.5,8.0,4.0,1003.0,30.0,47.0,34.5,26.0,28.0,34.5,323.05,29.0,2017-6,sylhet,0
sylhet2017-7,31.0,25.0,28.0,12.00,6.0,87.5,8.0,5.0,1003.0,30.0,61.0,33.5,26.0,28.0,33.5,166.92,28.0,2017-7,sylhet,0
sylhet2017-8,33.0,25.0,28.0,12.90,7.0,83.5,8.0,4.0,1004.0,30.0,48.0,35.0,25.0,29.0,35.0,170.41,31.0,2017-8,sylhet,0
sylhet2017-9,32.0,25.0,28.0,11.60,7.0,85.5,8.0,4.0,1007.0,30.0,41.0,34.0,25.0,28.0,34.0,176.26,28.0,2017-9,sylhet,0
sylhet2017-10,32.0,24.0,27.0,11.60,6.5,82.0,8.0,4.0,1008.0,30.0,29.0,32.5,24.5,28.0,32.5,168.88,20.0,2017-10,sylhet,0
sylhet2017-11,30.0,18.5,23.0,8.70,6.0,72.0,10.0,6.0,1012.0,30.0,2.0,28.0,20.0,25.0,28.0,8.47,4.0,2017-11,sylhet,0
sylhet2017-12,27.0,15.5,20.0,8.70,6.0,74.0,9.0,5.0,1015.0,30.0,2.5,24.0,18.0,23.0,23.0,27.92,7.0,2017-12,sylhet,0
sylhet2018-1,25.0,12.0,18.0,8.70,5.0,65.0,10.0,6.0,1014.0,30.0,0.0,21.0,14.0,20.5,20.5,4.46,1.0,2018-1,sylhet,0
sylhet2018-2,30.0,16.0,22.0,8.70,6.0,54.5,10.0,6.0,1013.0,30.0,7.0,24.0,13.0,23.0,23.5,1.60,1.0,2018-2,sylhet,0
sylhet2018-3,34.0,20.0,26.0,11.60,7.0,52.0,10.0,6.0,1011.0,30.0,7.5,28.5,16.0,27.5,28.5,37.11,10.0,2018-3,sylhet,0
sylhet2018-4,35.5,23.0,28.0,12.80,7.0,59.5,10.0,6.0,1009.5,30.0,20.0,31.0,19.0,29.0,31.0,85.57,24.0,2018-4,sylhet,0
sylhet2018-5,33.0,23.0,27.5,13.20,7.0,78.5,9.0,5.0,1007.5,30.0,34.5,32.0,23.0,28.0,32.0,147.60,24.0,2018-5,sylhet,0
sylhet2018-6,33.0,26.0,29.0,13.30,7.0,82.5,9.0,5.0,1002.5,30.0,41.5,35.0,25.0,29.0,35.0,271.87,28.0,2018-6,sylhet,0
sylhet2018-7,32.0,25.0,28.0,13.30,6.5,85.0,9.0,5.0,1001.0,30.0,47.5,35.0,26.0,29.0,35.0,123.97,24.0,2018-7,sylhet,0
sylhet2018-8,33.5,26.0,29.0,12.95,7.0,82.5,9.0,5.0,1001.5,30.0,43.5,35.0,25.0,29.0,35.0,100.67,28.0,2018-8,sylhet,0
sylhet2018-9,33.0,25.0,28.0,11.60,7.0,83.0,8.0,5.0,1007.0,30.0,33.5,33.5,25.0,28.0,33.5,101.08,24.0,2018-9,sylhet,0
sylhet2018-10,31.0,21.0,25.0,11.60,6.0,72.0,10.0,6.0,1012.0,30.0,15.0,29.5,21.5,27.0,29.5,60.87,14.0,2018-10,sylhet,0
sylhet2018-11,28.5,16.5,22.0,8.70,6.0,72.0,10.0,6.0,1014.0,30.0,2.0,25.0,18.0,24.0,24.5,19.30,6.0,2018-11,sylhet,0
sylhet2018-12,25.5,14.0,19.0,8.70,5.0,68.0,10.0,6.0,1015.0,30.0,3.0,22.0,15.0,21.0,21.0,20.50,3.0,2018-12,sylhet,0
sylhet2019-1,29.0,15.0,24.0,8.70,6.0,57.0,10.0,6.0,1016.0,30.0,1.0,23.0,12.0,22.0,23.0,1.00,2.0,2019-1,sylhet,0
sylhet2019-2,31.0,17.0,25.0,8.70,6.0,52.5,10.0,6.0,1015.0,30.0,10.0,24.0,11.5,23.0,24.0,82.50,7.0,2019-2,sylhet,0
sylhet2019-3,34.0,21.0,29.0,11.60,7.0,49.0,10.0,6.0,1011.5,30.0,16.0,28.0,14.5,27.5,28.0,69.00,12.0,2019-3,sylhet,0
sylhet2019-4,37.5,25.0,32.5,12.70,7.0,63.0,10.0,5.0,1009.0,30.0,39.0,32.0,21.0,31.0,32.0,352.20,21.0,2019-4,sylhet,0
sylhet2019-5,38.0,26.0,33.0,10.70,7.0,71.5,9.0,5.0,1006.0,30.0,58.5,36.0,24.0,31.0,36.0,471.80,31.0,2019-5,sylhet,0
sylhet2019-6,34.0,26.0,31.0,10.80,7.0,82.0,9.0,5.0,1002.5,30.0,68.5,35.0,26.0,29.0,35.0,601.00,30.0,2019-6,sylhet,0
sylhet2019-7,31.0,25.0,28.0,9.50,6.0,89.0,8.0,4.0,1002.0,30.0,76.0,33.0,25.0,27.0,33.0,538.90,31.0,2019-7,sylhet,0
sylhet2019-8,33.0,25.0,30.0,9.50,6.0,87.0,7.0,4.0,1003.0,30.0,71.0,34.0,25.5,28.0,34.0,511.40,30.0,2019-8,sylhet,0
sylhet2019-9,32.0,25.0,29.0,8.80,6.0,87.0,8.5,5.0,1007.0,30.0,67.5,33.0,25.0,28.0,32.5,295.30,30.0,2019-9,sylhet,0

In [14]:
tweet_data = pd.concat([ban_tweet,eng_tweet])

In [15]:
tweet_data

                datetime                                           location
0    2019-07-27 10:20:58                              chapainawabganj  ;
1    2019-07-30 08:20:04                              chapainawabganj  ;
2    2019-08-01 15:02:35                              chapainawabganj  ;
3    2019-08-04 12:11:43                              chapainawabganj  ;
4    2019-08-04 22:51:05                              chapainawabganj  ;
5    2019-08-04 23:20:53                              chapainawabganj  ;
6    2019-08-04 23:28:56                              chapainawabganj  ;
7    2019-08-05 00:29:34                              chapainawabganj  ;
8    2019-08-05 21:15:01                              chapainawabganj  ;
9    2019-08-06 11:06:15                              chapainawabganj  ;
10   2019-08-06 23:38:16                              chapainawabganj  ;
11   2019-08-06 23:38:50                              chapainawabganj  ;
12   2019-08-07 19:16:39                              chapainawabganj  ;
13   2019-08-10 18:02:03                              chapainawabganj  ;
14   2019-08-13 18:26:19                              chapainawabganj  ;
15   2019-08-14 11:12:11                              chapainawabganj  ;
16   2019-08-22 13:18:12                              chapainawabganj  ;
17   2019-07-27 15:12:06                 chapainawabganj  ;  hospital  ;
18   2019-07-27 23:12:52                 chapainawabganj  ;  hospital  ;
19   2019-07-28 08:58:35                 chapainawabganj  ;  hospital  ;
20   2019-07-28 23:46:22                 chapainawabganj  ;  hospital  ;
21   2019-08-03 17:41:20                 chapainawabganj  ;  hospital  ;
22   2019-08-08 00:32:39                 chapainawabganj  ;  hospital  ;
23   2019-07-25 21:28:44                                       narail  ;
24   2019-07-29 15:10:57                                       narail  ;
25   2019-07-29 16:14:16                                       narail  ;
26   2019-07-30 00:53:34                                       narail  ;
27   2019-07-30 01:20:53                                       narail  ;
28   2019-07-30 14:53:37                                       narail  ;
29   2019-07-30 21:51:19                                       narail  ;
...                  ...                                                ...
2219 2019-09-22 15:01:15                             dhaka  ;  hospital  ;
2220 2019-09-22 17:37:36              bangladesh  ;  dhaka  ;  hospital  ;
2221 2019-09-22 19:25:01                                     bangladesh  ;
2222 2019-09-22 23:20:53                                     bangladesh  ;
2223 2019-09-23 03:39:06                                     bangladesh  ;
2224 2019-09-23 05:48:00                                     bangladesh  ;
2225 2019-09-23 13:59:42                        bangladesh  ;  hospital  ;
2226 2019-09-23 14:01:16                             dhaka  ;  hospital  ;
2227 2019-09-23 23:39:39              bangladesh  ;  medical  ;  uttara  ;
2228 2019-09-24 00:49:00                             dhaka  ;  hospital  ;
2229 2019-09-24 01:29:07                           bangladesh  ;  dhaka  ;
2230 2019-09-24 10:07:55                                     bangladesh  ;
2231 2019-09-24 11:20:50                                     bangladesh  ;
2232 2019-09-24 12:21:10                                         khulna  ;
2233 2019-09-24 12:38:15  bangladesh  ;  medical  ;  khulna  ;  hospital...
2234 2019-09-24 12:39:07                bangladesh  ;  khulna  ;  dhaka  ;
2235 2019-09-24 13:03:24                             dhaka  ;  hospital  ;
2236 2019-09-24 13:07:17                medical  ;  khulna  ;  hospital  ;
2237 2019-09-24 13:11:38    medical  ;  khulna  ;  jashore  ;  hospital  ;
2238 2019-09-24 15:23:27                          bangladesh  ;  khulna  ;
2239 2019-09-24 21:59:40                                     bangladesh  ;
2240 2019-09-25 09:04:20                                         khulna  ;
2241 2019-09-25 10:20:35                                         khulna  ;
2242 2019-09-25 12:12:11                          bangladesh  ;  khulna  ;
2243 2019-09-25 13:01:25    medical  ;  khulna  ;  jashore  ;  hospital  ;
2244 2019-09-25 13:07:26                medical  ;  khulna  ;  hospital  ;
2245 2019-09-25 13:12:03                                         khulna  ;
2246 2019-09-25 13:13:04                bangladesh  ;  khulna  ;  dhaka  ;
2247 2019-09-25 16:07:23                                         khulna  ;
2248 2019-09-25 16:08:08                           bangladesh  ;  dhaka  ;

[28686 rows x 2 columns]

In [16]:
tweet_data = tweet_data.sample(frac=1).reset_index(drop=True)

In [17]:
tweet_data['location'].fillna("0",inplace=True)

In [18]:
loc_lst = list(tweet_data['location'])

In [19]:
for i in range(len(loc_lst)):
    if ' ' in loc_lst[i]:
        loc_lst[i] = loc_lst[i].replace(' ','')
for i in range(len(loc_lst)):
    if ' ' in loc_lst[i]:
        loc_lst[i] = loc_lst[i].replace(' ','')
for i in range(len(loc_lst)):
    if ' ' in loc_lst[i]:
        loc_lst[i] = loc_lst[i].replace(' ','')
for i in range(len(loc_lst)):
    if 'medical' in loc_lst[i]:
        loc_lst[i] = loc_lst[i].replace('medical','')
for i in range(len(loc_lst)):
    if 'hospital' in loc_lst[i]:
        loc_lst[i] = loc_lst[i].replace('hospital','')

In [20]:
loc_lst

['0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bogra;',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 'pabna;;',
 '0',
 '0',
 '0',
 'satkhira;',
 '0',
 '0',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;;',
 '0',
 'bangladesh;',
 '0',
 'narsingdi;',
 '0',
 '0',
 'bangladesh;',
 'bangladesh;;',
 'dhaka;',
 '0',
 '0',
 '0',
 '0',
 'chandpur;',
 '0',
 'bangladesh;',
 'nilphamari;',
 '0',
 'dhaka;',
 '0',
 'pabna;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';',
 'pabna;;',
 '0',
 'gazipur;',
 ';',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'rajshahi;',
 'naogaon;;',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 'bangladesh;',
 '0',
 ';khulna;jashore;;',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'mymensingh;noakhali;',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 'dhaka;',
 '0',
 '0',
 '0',
 '0',
 'barishal;barishal;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'dhaka;',
 'meherpur;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;;',
 '0',
 '0',
 '0',
 '0',
 'chittagong;',
 '0',
 '0',
 'barisal;',
 '0',
 'sylhet;',
 'dhaka;mirpur;',
 ';rangpur;lalmonirhat;;',
 '0',
 '0',
 'bangladesh;',
 '0',
 ';',
 '0',
 '0',
 'satkhira;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'kushtia;',
 '0',
 '0',
 'dhaka;',
 '0',
 '0',
 '0',
 'satkhira;',
 '0',
 '0',
 '0',
 'bagerhat;',
 '0',
 '0',
 ';',
 '0',
 '0',
 'jessore;',
 'barisal;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;;',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'rangpur;dinajpur;;',
 '0',
 'bangladesh;bogra;',
 '0',
 '0',
 'jhenaidah;',
 '0',
 '0',
 '0',
 'bogra;',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;dhaka;',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 'bangladesh;dhaka;',
 '0',
 'jhenaidah;',
 'bangladesh;',
 '0',
 'bangladesh;dhaka;',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'badda;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 'dhaka;;',
 '0',
 'satkhira;dhaka;',
 '0',
 '0',
 ';uttara;',
 '0',
 'bangladesh;',
 '0',
 '0',
 ';',
 '0',
 '0',
 '0',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';',
 'dhaka;;',
 'dhaka;',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 'dhaka;',
 '0',
 '0',
 'narail;',
 'jhenaidah;',
 '0',
 'bangladesh;',
 '0',
 ';',
 '0',
 '0',
 '0',
 'dhaka;',
 '0',
 ';',
 'bangladesh;;',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 'thakurgaon;',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'khulna;',
 '0',
 ';',
 '0',
 ';',
 'comilla;',
 '0',
 'habiganj;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;;',
 '0',
 'bagerhat;',
 '0',
 'dhaka;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 'dhaka;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'pabna;;',
 '0',
 '0',
 'dhaka;',
 '0',
 'bangladesh;',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 ';',
 ';',
 'thakurgaon;;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 'narsingdi;',
 '0',
 '0',
 'dhaka;',
 ';rajshahi;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'barisal;',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 ';',
 'bangladesh;',
 '0',
 'bangladesh;barisal;',
 '0',
 '0',
 '0',
 '0',
 'khulna;',
 '0',
 '0',
 'dhaka;;',
 '0',
 '0',
 '0',
 'dhaka;;',
 '0',
 '0',
 'bangladesh;;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 'patuakhali;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 'dhaka;;',
 'sylhet;',
 '0',
 'pabna;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'dhaka;',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 'satkhira;',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';',
 '0',
 '0',
 '0',
 '0',
 'pirojpur;',
 'kushtia;',
 'faridpur;;',
 '0',
 '0',
 '0',
 ';',
 '0',
 'habiganj;',
 '0',
 '0',
 'bangladesh;;',
 '0',
 '0',
 'sylhet;',
 '0',
 '0',
 'bangladesh;;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';',
 'dhaka;',
 'bangladesh;dhaka;mirpur;',
 ';',
 '0',
 '0',
 'barisal;barguna;',
 '0',
 '0',
 'barisal;',
 'sylhet;',
 'dhaka;;',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;dhaka;',
 'barisal;',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 'dhaka;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';',
 '0',
 '0',
 '0',
 'comilla;',
 '0',
 '0',
 '0',
 'gaibandha;',
 '0',
 'bangladesh;',
 '0',
 'bangladesh;;',
 '0',
 '0',
 ';',
 'bangladesh;khulna;dhaka;laxmipur;',
 '0',
 'dhaka;',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 'bangladesh;',
 ';',
 'bangladesh;dhaka;',
 '0',
 '0',
 ';tangail;;',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'kurigram;;',
 'dhaka;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'narail;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 ';',
 '0',
 'bangladesh;',
 'bangladesh;dhaka;',
 '0',
 'chittagong;',
 ';',
 '0',
 'moulvibazar;',
 '0',
 'bangladesh;',
 '0',
 '0',
 ';',
 '0',
 '0',
 'satkhira;',
 'bangladesh;dhaka;;',
 '0',
 ';',
 '0',
 'bangladesh;',
 'bangladesh;;',
 '0',
 'dhaka;',
 '0',
 'nilphamari;',
 '0',
 ';',
 '0',
 '0',
 'khulna;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'kushtia;jhenaidah;',
 'bagerhat;dhaka;;',
 'bangladesh;rangpur;dinajpur;dhaka;',
 '0',
 '0',
 ';',
 'bangladesh;',
 '0',
 '0',
 'satkhira;',
 'natore;',
 'kurigram;;',
 'bangladesh;',
 '0',
 'dhaka;noakhali;',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 'bangladesh;',
 '0',
 'bangladesh;',
 'dhaka;',
 '0',
 '0',
 '0',
 ';',
 '0',
 'dhaka;',
 '0',
 'brahmanbaria;;',
 '0',
 'bangladesh;dhaka;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;dhaka;',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';dhaka;dhakacollege;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 'bangladesh;',
 '0',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 'barishal;barishal;',
 '0',
 ';',
 '0',
 '0',
 '0',
 '0',
 'barisal;',
 '0',
 '0',
 '0',
 'sherpur;;',
 'sherpur;lakshmipur;',
 '0',
 '0',
 '0',
 '0',
 'dhaka;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'jessore;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';mymensingh;dhaka;noakhali;;',
 ';',
 'bangladesh;',
 'khulna;',
 '0',
 'dhaka;',
 'jessore;',
 '0',
 'kushtia;chuadanga;',
 '0',
 ';',
 '0',
 'dhaka;',
 '0',
 '0',
 'thakurgaon;',
 'khulna;',
 'thakurgaon;',
 '0',
 'dhaka;',
 '0',
 '0',
 '0',
 'kurigram;',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'dhaka;',
 '0',
 '0',
 'bangladesh;',
 '0',
 'pabna;;',
 '0',
 'bangladesh;barishal;dhaka;barishal;',
 '0',
 'bangladesh;',
 'bangladesh;dhaka;',
 '0',
 'bhola;',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 'laxmipur;',
 'bangladesh;',
 'bangladesh;;',
 'bangladesh;dhaka;',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 'kurigram;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;dhaka;;',
 '0',
 '0',
 '0',
 'bangladesh;',
 ';',
 '0',
 ';',
 '0',
 '0',
 'dhaka;',
 ';',
 'barguna;',
 '0',
 '0',
 '0',
 '0',
 '0',
 'dhaka;',
 '0',
 '0',
 ';',
 '0',
 'bangladesh;dhaka;',
 '0',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 ';',
 '0',
 '0',
 'dhaka;',
 '0',
 '0',
 '0',
 'jessore;',
 '0',
 'bangladesh;',
 '0',
 '0',
 '0',
 '0',
 'dhaka;',
 '0',
 'satkhira;dhaka;',
 '0',
 '0',
 '0',
 '0',
 ';',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'khulna;',
 '0',
 '0',
 '0',
 '0',
 'bhola;',
 '0',
 'bangladesh;',
 'dhaka;;',
 '0',
 ';',
 '0',
 'bangladesh;',
 'bangladesh;dhaka;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'bangladesh;dhaka;',
 '0',
 ';',
 ';;',
 '0',
 'narail;;',
 'kushtia;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'dhaka;',
 '0',
 'bangladesh;',
 '0',
 'dhaka;',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 'sunamganj;',
 '0',
 '0',
 '0',
 'bangladesh;',
 'bangladesh;dhaka;mirpur;',
 '0',
 '0',
 '0',
 '0',
 ...]

In [21]:
for i in range(len(loc_lst)):
    if '00' in loc_lst[i]:
        loc_lst[i] = loc_lst[i].replace('00','0')
for i in range(len(loc_lst)):
    if ';' in loc_lst[i] and (len(loc_lst[i]) > 3):
        loc_lst[i] = loc_lst[i].split(';')
    elif ';' in loc_lst[i]:
        loc_lst[i] = loc_lst[i].replace(';','0')
    else:
        loc_lst[i] = [loc_lst[i]]
for i in range(len(loc_lst)):
    if type(loc_lst[i]) != list:
        loc_lst[i] = [loc_lst[i]]
for i in range(len(loc_lst)):
    if '' in loc_lst[i]:
        loc_lst[i].remove('')
for i in range(len(loc_lst)):
    if '' in loc_lst[i]:
        loc_lst[i].remove('')
for i in range(len(loc_lst)):
    if '' in loc_lst[i]:
        loc_lst[i].remove('')

In [22]:
loc_lst

[['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bogra'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['pabna'],
 ['0'],
 ['0'],
 ['0'],
 ['satkhira'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['narsingdi'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['bangladesh'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['chandpur'],
 ['0'],
 ['bangladesh'],
 ['nilphamari'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['pabna'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['pabna'],
 ['0'],
 ['gazipur'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['rajshahi'],
 ['naogaon'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['bangladesh'],
 ['0'],
 ['khulna', 'jashore'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['mymensingh', 'noakhali'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['barishal', 'barishal'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['meherpur'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['chittagong'],
 ['0'],
 ['0'],
 ['barisal'],
 ['0'],
 ['sylhet'],
 ['dhaka', 'mirpur'],
 ['rangpur', 'lalmonirhat'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['satkhira'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['kushtia'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['satkhira'],
 ['0'],
 ['0'],
 ['0'],
 ['bagerhat'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['jessore'],
 ['barisal'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['rangpur', 'dinajpur'],
 ['0'],
 ['bangladesh', 'bogra'],
 ['0'],
 ['0'],
 ['jhenaidah'],
 ['0'],
 ['0'],
 ['0'],
 ['bogra'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['jhenaidah'],
 ['bangladesh'],
 ['0'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['badda'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['satkhira', 'dhaka'],
 ['0'],
 ['0'],
 ['uttara'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['narail'],
 ['jhenaidah'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['thakurgaon'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['khulna'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['comilla'],
 ['0'],
 ['habiganj'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['bagerhat'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['pabna'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['bangladesh'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['thakurgaon'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['narsingdi'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['rajshahi'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['barisal'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['bangladesh', 'barisal'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['khulna'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['patuakhali'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['dhaka'],
 ['sylhet'],
 ['0'],
 ['pabna'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['satkhira'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['pirojpur'],
 ['kushtia'],
 ['faridpur'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['habiganj'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['sylhet'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['bangladesh', 'dhaka', 'mirpur'],
 ['0'],
 ['0'],
 ['0'],
 ['barisal', 'barguna'],
 ['0'],
 ['0'],
 ['barisal'],
 ['sylhet'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh', 'dhaka'],
 ['barisal'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['comilla'],
 ['0'],
 ['0'],
 ['0'],
 ['gaibandha'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh', 'khulna', 'dhaka', 'laxmipur'],
 ['0'],
 ['dhaka'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['bangladesh'],
 ['0'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['0'],
 ['tangail'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['kurigram'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['narail'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['chittagong'],
 ['0'],
 ['0'],
 ['moulvibazar'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['satkhira'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['bangladesh'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['nilphamari'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['khulna'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['kushtia', 'jhenaidah'],
 ['bagerhat', 'dhaka'],
 ['bangladesh', 'rangpur', 'dinajpur', 'dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['satkhira'],
 ['natore'],
 ['kurigram'],
 ['bangladesh'],
 ['0'],
 ['dhaka', 'noakhali'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['bangladesh'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['brahmanbaria'],
 ['0'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka', 'dhakacollege'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['barishal', 'barishal'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['barisal'],
 ['0'],
 ['0'],
 ['0'],
 ['sherpur'],
 ['sherpur', 'lakshmipur'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['jessore'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['mymensingh', 'dhaka', 'noakhali'],
 ['0'],
 ['bangladesh'],
 ['khulna'],
 ['0'],
 ['dhaka'],
 ['jessore'],
 ['0'],
 ['kushtia', 'chuadanga'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['thakurgaon'],
 ['khulna'],
 ['thakurgaon'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['kurigram'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['pabna'],
 ['0'],
 ['bangladesh', 'barishal', 'dhaka', 'barishal'],
 ['0'],
 ['bangladesh'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['bhola'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['laxmipur'],
 ['bangladesh'],
 ['bangladesh'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['kurigram'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['barguna'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['jessore'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['satkhira', 'dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['khulna'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bhola'],
 ['0'],
 ['bangladesh'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh', 'dhaka'],
 ['0'],
 ['0'],
 ['00'],
 ['0'],
 ['narail'],
 ['kushtia'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['bangladesh'],
 ['0'],
 ['dhaka'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ['sunamganj'],
 ['0'],
 ['0'],
 ['0'],
 ['bangladesh'],
 ['bangladesh', 'dhaka', 'mirpur'],
 ['0'],
 ['0'],
 ['0'],
 ['0'],
 ...]

In [23]:
tweet_data['location'] = loc_lst
tweet_data.head(10)

             datetime      location
0 2019-08-07 00:11:01           [0]
1 2019-07-25 17:00:25           [0]
2 2019-07-22 13:39:12           [0]
3 2019-08-22 13:43:19  [bangladesh]
4 2019-08-02 10:52:51           [0]
5 2019-07-29 08:53:45           [0]
6 2019-08-01 18:32:35           [0]
7 2019-07-28 19:47:50           [0]
8 2019-07-27 14:16:42           [0]
9 2019-08-09 14:26:20       [bogra]

In [24]:
tweet_data.sort_values('datetime',inplace=True)

In [25]:
tweet_data = tweet_data[tweet_data['datetime']>='2015-01-01 00:00:00']

In [26]:
tweet_data.index = [i for i in range(len(tweet_data))]

In [27]:
tweet_data['year_month'] = [str(np.array(tweet_data['datetime'])[i]).split('T')[0] for i in range(len(tweet_data))]

In [30]:
tweet_data.head(500)

               datetime         location  year_month
0   2015-01-01 00:47:41              [0]  2015-01-01
1   2015-01-12 19:47:43     [bangladesh]  2015-01-12
2   2015-01-17 03:54:21              [0]  2015-01-17
3   2015-01-19 16:19:29              [0]  2015-01-19
4   2015-01-19 23:11:12              [0]  2015-01-19
5   2015-01-21 21:20:39              [0]  2015-01-21
6   2015-01-23 10:18:18              [0]  2015-01-23
7   2015-01-23 10:19:17              [0]  2015-01-23
8   2015-01-26 20:19:47              [0]  2015-01-26
9   2015-01-28 08:53:51              [0]  2015-01-28
10  2015-01-29 01:20:51              [0]  2015-01-29
11  2015-01-29 01:30:33              [0]  2015-01-29
12  2015-01-29 01:48:53              [0]  2015-01-29
13  2015-01-29 08:00:52          [bogra]  2015-01-29
14  2015-01-29 08:25:16              [0]  2015-01-29
15  2015-01-29 11:08:52              [0]  2015-01-29
16  2015-01-29 12:19:19              [0]  2015-01-29
17  2015-01-29 15:03:19              [0]  2015-01-29
18  2015-01-29 20:08:08              [0]  2015-01-29
19  2015-01-29 20:30:20              [0]  2015-01-29
20  2015-01-30 14:31:20              [0]  2015-01-30
21  2015-01-30 15:22:31              [0]  2015-01-30
22  2015-01-30 23:22:50              [0]  2015-01-30
23  2015-02-05 17:30:03              [0]  2015-02-05
24  2015-02-05 20:50:48              [0]  2015-02-05
25  2015-02-17 15:15:20          [dhaka]  2015-02-17
26  2015-02-17 15:15:40          [dhaka]  2015-02-17
27  2015-02-24 19:15:58              [0]  2015-02-24
28  2015-03-03 13:12:57              [0]  2015-03-03
29  2015-03-05 04:47:53              [0]  2015-03-05
..                  ...              ...         ...
470 2015-10-03 10:44:50  [dhaka, mirpur]  2015-10-03
471 2015-10-03 12:21:52              [0]  2015-10-03
472 2015-10-03 13:43:26              [0]  2015-10-03
473 2015-10-03 17:17:55              [0]  2015-10-03
474 2015-10-03 17:39:45              [0]  2015-10-03
475 2015-10-03 17:40:28     [bangladesh]  2015-10-03
476 2015-10-03 18:00:45     [bangladesh]  2015-10-03
477 2015-10-03 18:46:14              [0]  2015-10-03
478 2015-10-03 19:20:53              [0]  2015-10-03
479 2015-10-03 21:45:49              [0]  2015-10-03
480 2015-10-03 23:32:00              [0]  2015-10-03
481 2015-10-03 23:41:38              [0]  2015-10-03
482 2015-10-04 00:48:52     [bangladesh]  2015-10-04
483 2015-10-04 00:49:02     [bangladesh]  2015-10-04
484 2015-10-04 01:22:29              [0]  2015-10-04
485 2015-10-04 01:23:48              [0]  2015-10-04
486 2015-10-04 01:32:16              [0]  2015-10-04
487 2015-10-04 02:18:59              [0]  2015-10-04
488 2015-10-04 09:40:27              [0]  2015-10-04
489 2015-10-04 11:45:34              [0]  2015-10-04
490 2015-10-04 17:08:30              [0]  2015-10-04
491 2015-10-04 17:08:42              [0]  2015-10-04
492 2015-10-04 17:08:47              [0]  2015-10-04
493 2015-10-04 17:08:51              [0]  2015-10-04
494 2015-10-04 17:08:55              [0]  2015-10-04
495 2015-10-04 17:09:04              [0]  2015-10-04
496 2015-10-04 17:09:23              [0]  2015-10-04
497 2015-10-04 17:09:33              [0]  2015-10-04
498 2015-10-04 17:29:06              [0]  2015-10-04
499 2015-10-04 17:29:13              [0]  2015-10-04

[500 rows x 3 columns]

In [31]:
temp_date = []
for i in range(len(tweet_data)):
    temp2 = str(np.array(tweet_data['year_month'])[i]).split('-')[1]
    if '10' in temp2 :
        temp2 = temp2.replace('10','10')
    elif '0' in temp2:
        temp2 = temp2.replace('0','')
    temp1 = str(np.array(tweet_data['year_month'])[i]).split('-')[0]
    temp_date.append(temp1+'-'+temp2)

In [32]:
tweet_data['year_month'] = temp_date

In [33]:
tweet_data.head(500)

               datetime         location year_month
0   2015-01-01 00:47:41              [0]     2015-1
1   2015-01-12 19:47:43     [bangladesh]     2015-1
2   2015-01-17 03:54:21              [0]     2015-1
3   2015-01-19 16:19:29              [0]     2015-1
4   2015-01-19 23:11:12              [0]     2015-1
5   2015-01-21 21:20:39              [0]     2015-1
6   2015-01-23 10:18:18              [0]     2015-1
7   2015-01-23 10:19:17              [0]     2015-1
8   2015-01-26 20:19:47              [0]     2015-1
9   2015-01-28 08:53:51              [0]     2015-1
10  2015-01-29 01:20:51              [0]     2015-1
11  2015-01-29 01:30:33              [0]     2015-1
12  2015-01-29 01:48:53              [0]     2015-1
13  2015-01-29 08:00:52          [bogra]     2015-1
14  2015-01-29 08:25:16              [0]     2015-1
15  2015-01-29 11:08:52              [0]     2015-1
16  2015-01-29 12:19:19              [0]     2015-1
17  2015-01-29 15:03:19              [0]     2015-1
18  2015-01-29 20:08:08              [0]     2015-1
19  2015-01-29 20:30:20              [0]     2015-1
20  2015-01-30 14:31:20              [0]     2015-1
21  2015-01-30 15:22:31              [0]     2015-1
22  2015-01-30 23:22:50              [0]     2015-1
23  2015-02-05 17:30:03              [0]     2015-2
24  2015-02-05 20:50:48              [0]     2015-2
25  2015-02-17 15:15:20          [dhaka]     2015-2
26  2015-02-17 15:15:40          [dhaka]     2015-2
27  2015-02-24 19:15:58              [0]     2015-2
28  2015-03-03 13:12:57              [0]     2015-3
29  2015-03-05 04:47:53              [0]     2015-3
..                  ...              ...        ...
470 2015-10-03 10:44:50  [dhaka, mirpur]    2015-10
471 2015-10-03 12:21:52              [0]    2015-10
472 2015-10-03 13:43:26              [0]    2015-10
473 2015-10-03 17:17:55              [0]    2015-10
474 2015-10-03 17:39:45              [0]    2015-10
475 2015-10-03 17:40:28     [bangladesh]    2015-10
476 2015-10-03 18:00:45     [bangladesh]    2015-10
477 2015-10-03 18:46:14              [0]    2015-10
478 2015-10-03 19:20:53              [0]    2015-10
479 2015-10-03 21:45:49              [0]    2015-10
480 2015-10-03 23:32:00              [0]    2015-10
481 2015-10-03 23:41:38              [0]    2015-10
482 2015-10-04 00:48:52     [bangladesh]    2015-10
483 2015-10-04 00:49:02     [bangladesh]    2015-10
484 2015-10-04 01:22:29              [0]    2015-10
485 2015-10-04 01:23:48              [0]    2015-10
486 2015-10-04 01:32:16              [0]    2015-10
487 2015-10-04 02:18:59              [0]    2015-10
488 2015-10-04 09:40:27              [0]    2015-10
489 2015-10-04 11:45:34              [0]    2015-10
490 2015-10-04 17:08:30              [0]    2015-10
491 2015-10-04 17:08:42              [0]    2015-10
492 2015-10-04 17:08:47              [0]    2015-10
493 2015-10-04 17:08:51              [0]    2015-10
494 2015-10-04 17:08:55              [0]    2015-10
495 2015-10-04 17:09:04              [0]    2015-10
496 2015-10-04 17:09:23              [0]    2015-10
497 2015-10-04 17:09:33              [0]    2015-10
498 2015-10-04 17:29:06              [0]    2015-10
499 2015-10-04 17:29:13              [0]    2015-10

[500 rows x 3 columns]

In [34]:
tweet_data.columns = ['datetime','location','date']

In [35]:
for i in range(len(tweet_data)):
    for j in range(len(tweet_data['location'][i])):
        if tweet_data['location'][i][j] == 'badda':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'cantornment':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'chawkbazar':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'dhanmondi':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'gulshan':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'jatrabari':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'kafrul':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'khilgaon':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'mirpur':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'mohammadpur':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'new market':
            tweet_data['location'][i][j] = 'dhaka'
        if tweet_data['location'][i][j] == 'uttara':
            tweet_data['location'][i][j] = 'dhaka'

In [36]:
tweet_data.head(500)

               datetime        location     date
0   2015-01-01 00:47:41             [0]   2015-1
1   2015-01-12 19:47:43    [bangladesh]   2015-1
2   2015-01-17 03:54:21             [0]   2015-1
3   2015-01-19 16:19:29             [0]   2015-1
4   2015-01-19 23:11:12             [0]   2015-1
5   2015-01-21 21:20:39             [0]   2015-1
6   2015-01-23 10:18:18             [0]   2015-1
7   2015-01-23 10:19:17             [0]   2015-1
8   2015-01-26 20:19:47             [0]   2015-1
9   2015-01-28 08:53:51             [0]   2015-1
10  2015-01-29 01:20:51             [0]   2015-1
11  2015-01-29 01:30:33             [0]   2015-1
12  2015-01-29 01:48:53             [0]   2015-1
13  2015-01-29 08:00:52         [bogra]   2015-1
14  2015-01-29 08:25:16             [0]   2015-1
15  2015-01-29 11:08:52             [0]   2015-1
16  2015-01-29 12:19:19             [0]   2015-1
17  2015-01-29 15:03:19             [0]   2015-1
18  2015-01-29 20:08:08             [0]   2015-1
19  2015-01-29 20:30:20             [0]   2015-1
20  2015-01-30 14:31:20             [0]   2015-1
21  2015-01-30 15:22:31             [0]   2015-1
22  2015-01-30 23:22:50             [0]   2015-1
23  2015-02-05 17:30:03             [0]   2015-2
24  2015-02-05 20:50:48             [0]   2015-2
25  2015-02-17 15:15:20         [dhaka]   2015-2
26  2015-02-17 15:15:40         [dhaka]   2015-2
27  2015-02-24 19:15:58             [0]   2015-2
28  2015-03-03 13:12:57             [0]   2015-3
29  2015-03-05 04:47:53             [0]   2015-3
..                  ...             ...      ...
470 2015-10-03 10:44:50  [dhaka, dhaka]  2015-10
471 2015-10-03 12:21:52             [0]  2015-10
472 2015-10-03 13:43:26             [0]  2015-10
473 2015-10-03 17:17:55             [0]  2015-10
474 2015-10-03 17:39:45             [0]  2015-10
475 2015-10-03 17:40:28    [bangladesh]  2015-10
476 2015-10-03 18:00:45    [bangladesh]  2015-10
477 2015-10-03 18:46:14             [0]  2015-10
478 2015-10-03 19:20:53             [0]  2015-10
479 2015-10-03 21:45:49             [0]  2015-10
480 2015-10-03 23:32:00             [0]  2015-10
481 2015-10-03 23:41:38             [0]  2015-10
482 2015-10-04 00:48:52    [bangladesh]  2015-10
483 2015-10-04 00:49:02    [bangladesh]  2015-10
484 2015-10-04 01:22:29             [0]  2015-10
485 2015-10-04 01:23:48             [0]  2015-10
486 2015-10-04 01:32:16             [0]  2015-10
487 2015-10-04 02:18:59             [0]  2015-10
488 2015-10-04 09:40:27             [0]  2015-10
489 2015-10-04 11:45:34             [0]  2015-10
490 2015-10-04 17:08:30             [0]  2015-10
491 2015-10-04 17:08:42             [0]  2015-10
492 2015-10-04 17:08:47             [0]  2015-10
493 2015-10-04 17:08:51             [0]  2015-10
494 2015-10-04 17:08:55             [0]  2015-10
495 2015-10-04 17:09:04             [0]  2015-10
496 2015-10-04 17:09:23             [0]  2015-10
497 2015-10-04 17:09:33             [0]  2015-10
498 2015-10-04 17:29:06             [0]  2015-10
499 2015-10-04 17:29:13             [0]  2015-10

[500 rows x 3 columns]

In [37]:
c = 0
for i in range(len(data)):
    
    for j in range(len(tweet_data)):
        for k in range(len(tweet_data['location'][j])):
            try:
                str1 = tweet_data['location'][j][k].lower()
                str2 = data['locations'][i].lower()

                if str1 == str2 and tweet_data['date'][j] == data['date'][i]:
                    data['label'][i] = data['label'][i]+1
                
            except: 
                print('Error')
                pass
            c+=1
            if c%1000000 == 0:
                print(str(c)+'\n')

1000000

C:\Users\onyho\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

2000000

3000000

4000000

5000000

6000000

7000000

8000000

9000000

10000000

11000000

12000000

13000000

14000000

15000000

16000000

17000000

18000000

19000000

20000000

21000000

22000000

23000000

24000000

25000000

26000000

27000000

28000000

29000000

30000000

31000000

32000000

33000000

34000000

35000000

36000000

37000000

38000000

39000000

40000000

41000000

42000000

43000000

44000000

45000000

46000000

47000000

48000000

49000000

50000000

51000000

52000000

53000000

54000000

55000000

56000000

57000000

58000000

59000000

60000000

61000000

62000000

63000000

64000000

65000000

66000000

67000000

68000000

69000000

70000000

71000000

72000000

73000000

74000000

75000000

In [39]:
data

,maxtempC,mintempC,avgtempC,sunHour,uvIndex,humidity,visibility,visibilityMiles,pressure,pressureInches,cloudcover,HeatIndexC,DewPointC,WindChillC,FeelsLikeC,rainFall,rainDays,date,locations,label
locations_month,,,,,,,,,,,,,,,,,,,,
barisal2015-1,26.0,17.0,21.0,8.70,6.0,53.0,10.0,6.0,1015.0,30.0,1.5,24.0,13.0,23.0,23.0,10.17,3.0,2015-1,barisal,0
barisal2015-2,28.0,19.0,23.0,8.70,6.0,55.5,10.0,6.0,1013.5,30.0,9.5,26.0,14.0,25.0,26.0,2.26,3.0,2015-2,barisal,0
barisal2015-3,33.0,22.0,27.0,11.60,7.0,50.5,10.0,6.0,1011.0,30.0,13.0,30.0,16.0,29.0,30.0,4.83,14.0,2015-3,barisal,0
barisal2015-4,33.0,26.5,29.0,12.75,7.0,67.5,10.0,6.0,1008.0,30.0,31.5,34.0,23.0,30.0,34.0,44.09,16.0,2015-4,barisal,0
barisal2015-5,35.0,28.0,31.0,13.10,8.0,69.5,10.0,6.0,1005.0,30.0,37.5,38.0,25.0,32.0,38.0,20.35,15.0,2015-5,barisal,0
barisal2015-6,33.0,29.0,31.0,12.00,8.0,70.0,10.0,6.0,1002.0,30.0,45.5,37.0,25.0,31.0,37.0,29.66,18.0,2015-6,barisal,0
barisal2015-7,32.0,27.5,29.5,12.00,7.0,77.0,10.0,6.0,999.0,30.0,57.5,35.0,25.0,30.0,35.0,68.01,26.0,2015-7,barisal,0
barisal2015-8,32.0,28.0,30.0,12.85,7.0,77.0,10.0,6.0,1003.0,30.0,45.5,36.0,25.0,30.0,36.0,38.65,21.0,2015-8,barisal,0
barisal2015-9,32.0,27.0,29.0,11.85,7.0,76.0,10.0,6.0,1005.0,30.0,38.5,35.0,25.0,30.0,35.0,80.97,24.0,2015-9,barisal,0
barisal2015-10,31.0,24.0,27.0,11.60,7.0,74.5,10.0,6.0,1010.5,30.0,26.0,32.0,24.0,29.0,32.0,36.15,18.0,2015-10,barisal,0
barisal2015-11,29.0,21.0,24.0,8.70,6.0,65.0,10.0,6.0,1013.0,30.0,1.0,29.0,20.0,27.0,29.0,3.09,4.0,2015-11,barisal,0
barisal2015-12,26.0,19.0,21.5,8.70,6.0,61.0,10.0,6.0,1015.0,30.0,14.0,25.0,15.5,23.0,24.0,9.67,8.0,2015-12,barisal,0
barisal2016-1,26.0,17.0,21.0,8.70,6.0,53.0,10.0,6.0,1015.0,30.0,2.0,25.0,13.0,23.0,23.5,0.64,2.0,2016-1,barisal,0
barisal2016-2,30.0,21.5,25.5,8.70,6.5,57.5,10.0,6.0,1014.0,30.0,9.0,28.5,18.0,27.0,28.5,7.40,5.0,2016-2,barisal,0
barisal2016-3,34.0,25.0,29.0,11.60,7.0,54.0,10.0,6.0,1011.0,30.0,10.5,32.0,19.0,30.0,32.0,9.57,8.0,2016-3,barisal,0
barisal2016-4,35.0,27.0,30.5,12.70,8.0,68.0,10.0,6.0,1006.5,30.0,38.0,36.0,24.0,31.0,36.0,13.23,11.0,2016-4,barisal,0
barisal2016-5,34.5,28.0,31.0,13.10,8.0,70.5,10.0,6.0,1004.0,30.0,29.0,38.0,25.0,31.0,38.0,30.49,19.0,2016-5,barisal,0
barisal2016-6,33.0,28.0,30.0,13.30,7.5,75.0,10.0,6.0,1003.0,30.0,34.0,37.0,25.0,30.0,37.0,76.37,22.0,2016-6,barisal,0
barisal2016-7,33.0,27.0,30.0,13.10,6.0,78.0,9.0,5.0,1000.0,30.0,54.5,36.0,25.0,30.0,36.0,58.77,28.0,2016-7,barisal,0
barisal2016-8,33.0,27.0,29.0,12.80,7.0,77.0,10.0,6.0,1002.0,30.0,36.5,36.0,25.0,30.0,36.0,57.96,22.0,2016-8,barisal,0
barisal2016-9,32.0,27.0,29.0,11.60,7.0,78.5,10.0,5.0,1005.0,30.0,34.0,36.0,25.0,30.0,36.0,61.99,23.0,2016-9,barisal,0
barisal2016-10,31.0,25.0,27.5,11.60,7.0,76.5,10.0,6.0,1007.0,30.0,21.0,34.0,25.0,29.0,34.0,20.45,14.0,2016-10,barisal,0
barisal2016-11,28.0,19.5,23.0,8.70,6.0,67.5,10.0,6.0,1012.0,30.0,2.0,28.0,20.0,26.0,28.0,19.37,4.0,2016-11,barisal,0
barisal2016-12,27.0,17.0,22.0,8.70,6.0,59.5,10.0,6.0,1014.0,30.0,0.0,26.0,16.0,25.0,25.0,0.00,0.0,2016-12,barisal,0
barisal2017-1,27.0,16.0,21.0,8.70,6.0,47.0,10.0,6.0,1015.0,30.0,0.0,24.0,11.0,23.0,23.0,0.00,0.0,2017-1,barisal,0
barisal2017-2,30.0,19.0,24.0,8.70,6.0,46.5,10.0,6.0,1013.0,30.0,1.0,27.0,13.0,26.0,27.0,1.25,1.0,2017-2,barisal,0
barisal2017-3,31.0,21.5,26.0,11.60,7.0,66.5,10.0,6.0,1010.0,30.0,14.5,29.0,19.5,27.0,29.0,8.43,9.0,2017-3,barisal,0
barisal2017-4,33.5,26.0,29.0,11.90,7.0,74.0,10.0,6.0,1008.0,30.0,40.5,34.0,24.0,29.5,34.0,8.06,7.0,2017-4,barisal,0
barisal2017-5,36.0,28.0,31.0,13.10,8.0,68.5,10.0,6.0,1004.0,30.0,24.5,38.5,25.0,32.0,38.5,17.34,11.0,2017-5,barisal,0
barisal2017-6,33.0,28.0,30.0,13.30,7.0,77.0,10.0,6.0,1001.0,30.0,36.5,37.0,25.0,30.0,37.0,59.52,21.0,2017-6,barisal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sylhet2017-4,32.0,23.0,27.0,11.95,6.0,85.5,8.0,4.0,1009.0,30.0,40.5,30.0,23.0,27.0,30.0,256.14,20.0,2017-4,sylhet,0
sylhet2017-5,34.0,25.0,28.5,13.20,7.0,76.0,10.0,6.0,1006.0,30.0,17.0,34.0,24.0,29.5,34.0,109.26,21.0,2017-5,sylhet,0
sylhet2017-6,33.0,25.0,28.0,13.35,6.5,86.5,8.0,4.0,1003.0,30.0,47.0,34.5,26.0,28.0,34.5,323.05,29.0,2017-6,sylhet,0
sylhet2017-7,31.0,25.0,28.0,12.00,6.0,87.5,8.0,5.0,1003.0,30.0,61.0,33.5,26.0,28.0,33.5,166.92,28.0,2017-7,sylhet,0
sylhet2017-8,33.0,25.0,28.0,12.90,7.0,83.5,8.0,4.0,1004.0,30.0,48.0,35.0,25.0,29.0,35.0,170.41,31.0,2017-8,sylhet,0
sylhet2017-9,32.0,25.0,28.0,11.60,7.0,85.5,8.0,4.0,1007.0,30.0,41.0,34.0,25.0,28.0,34.0,176.26,28.0,2017-9,sylhet,0
sylhet2017-10,32.0,24.0,27.0,11.60,6.5,82.0,8.0,4.0,1008.0,30.0,29.0,32.5,24.5,28.0,32.5,168.88,20.0,2017-10,sylhet,0
sylhet2017-11,30.0,18.5,23.0,8.70,6.0,72.0,10.0,6.0,1012.0,30.0,2.0,28.0,20.0,25.0,28.0,8.47,4.0,2017-11,sylhet,0
sylhet2017-12,27.0,15.5,20.0,8.70,6.0,74.0,9.0,5.0,1015.0,30.0,2.5,24.0,18.0,23.0,23.0,27.92,7.0,2017-12,sylhet,0
sylhet2018-1,25.0,12.0,18.0,8.70,5.0,65.0,10.0,6.0,1014.0,30.0,0.0,21.0,14.0,20.5,20.5,4.46,1.0,2018-1,sylhet,0
sylhet2018-2,30.0,16.0,22.0,8.70,6.0,54.5,10.0,6.0,1013.0,30.0,7.0,24.0,13.0,23.0,23.5,1.60,1.0,2018-2,sylhet,0
sylhet2018-3,34.0,20.0,26.0,11.60,7.0,52.0,10.0,6.0,1011.0,30.0,7.5,28.5,16.0,27.5,28.5,37.11,10.0,2018-3,sylhet,0
sylhet2018-4,35.5,23.0,28.0,12.80,7.0,59.5,10.0,6.0,1009.5,30.0,20.0,31.0,19.0,29.0,31.0,85.57,24.0,2018-4,sylhet,0
sylhet2018-5,33.0,23.0,27.5,13.20,7.0,78.5,9.0,5.0,1007.5,30.0,34.5,32.0,23.0,28.0,32.0,147.60,24.0,2018-5,sylhet,0
sylhet2018-6,33.0,26.0,29.0,13.30,7.0,82.5,9.0,5.0,1002.5,30.0,41.5,35.0,25.0,29.0,35.0,271.87,28.0,2018-6,sylhet,0
sylhet2018-7,32.0,25.0,28.0,13.30,6.5,85.0,9.0,5.0,1001.0,30.0,47.5,35.0,26.0,29.0,35.0,123.97,24.0,2018-7,sylhet,0
sylhet2018-8,33.5,26.0,29.0,12.95,7.0,82.5,9.0,5.0,1001.5,30.0,43.5,35.0,25.0,29.0,35.0,100.67,28.0,2018-8,sylhet,1
sylhet2018-9,33.0,25.0,28.0,11.60,7.0,83.0,8.0,5.0,1007.0,30.0,33.5,33.5,25.0,28.0,33.5,101.08,24.0,2018-9,sylhet,0
sylhet2018-10,31.0,21.0,25.0,11.60,6.0,72.0,10.0,6.0,1012.0,30.0,15.0,29.5,21.5,27.0,29.5,60.87,14.0,2018-10,sylhet,0
sylhet2018-11,28.5,16.5,22.0,8.70,6.0,72.0,10.0,6.0,1014.0,30.0,2.0,25.0,18.0,24.0,24.5,19.30,6.0,2018-11,sylhet,0
sylhet2018-12,25.5,14.0,19.0,8.70,5.0,68.0,10.0,6.0,1015.0,30.0,3.0,22.0,15.0,21.0,21.0,20.50,3.0,2018-12,sylhet,0
sylhet2019-1,29.0,15.0,24.0,8.70,6.0,57.0,10.0,6.0,1016.0,30.0,1.0,23.0,12.0,22.0,23.0,1.00,2.0,2019-1,sylhet,0
sylhet2019-2,31.0,17.0,25.0,8.70,6.0,52.5,10.0,6.0,1015.0,30.0,10.0,24.0,11.5,23.0,24.0,82.50,7.0,2019-2,sylhet,0
sylhet2019-3,34.0,21.0,29.0,11.60,7.0,49.0,10.0,6.0,1011.5,30.0,16.0,28.0,14.5,27.5,28.0,69.00,12.0,2019-3,sylhet,0
sylhet2019-4,37.5,25.0,32.5,12.70,7.0,63.0,10.0,5.0,1009.0,30.0,39.0,32.0,21.0,31.0,32.0,352.20,21.0,2019-4,sylhet,0
sylhet2019-5,38.0,26.0,33.0,10.70,7.0,71.5,9.0,5.0,1006.0,30.0,58.5,36.0,24.0,31.0,36.0,471.80,31.0,2019-5,sylhet,0
sylhet2019-6,34.0,26.0,31.0,10.80,7.0,82.0,9.0,5.0,1002.5,30.0,68.5,35.0,26.0,29.0,35.0,601.00,30.0,2019-6,sylhet,0
sylhet2019-7,31.0,25.0,28.0,9.50,6.0,89.0,8.0,4.0,1002.0,30.0,76.0,33.0,25.0,27.0,33.0,538.90,31.0,2019-7,sylhet,44
sylhet2019-8,33.0,25.0,30.0,9.50,6.0,87.0,7.0,4.0,1003.0,30.0,71.0,34.0,25.5,28.0,34.0,511.40,30.0,2019-8,sylhet,91
sylhet2019-9,32.0,25.0,29.0,8.80,6.0,87.0,8.5,5.0,1007.0,30.0,67.5,33.0,25.0,28.0,32.5,295.30,30.0,2019-9,sylhet,7

In [40]:
labels = data.groupby('label')
labels.groups

{0: Index(['barisal2015-1', 'barisal2015-2', 'barisal2015-3', 'barisal2015-4',
        'barisal2015-5', 'barisal2015-6', 'barisal2015-7', 'barisal2015-8',
        'barisal2015-9', 'barisal2015-10',
        ...
        'sylhet2018-9', 'sylhet2018-10', 'sylhet2018-11', 'sylhet2018-12',
        'sylhet2019-1', 'sylhet2019-2', 'sylhet2019-3', 'sylhet2019-4',
        'sylhet2019-5', 'sylhet2019-6'],
       dtype='object', name='locations_month', length=2365),
 1: Index(['barisal2018-4', 'pirojpur2015-9', 'pirojpur2019-7', 'bandarban2019-9',
        'brahmanbaria2019-9', 'chittagong2016-8', 'chittagong2017-5',
        'chittagong2017-6', 'chittagong2017-9', 'chittagong2018-3',
        'chittagong2019-5', 'comilla2017-7', 'comilla2017-11',
        'khagrachhari2019-8', 'noakhali2017-1', 'noakhali2018-7',
        'rangamati2018-7', 'rangamati2018-8', 'dhaka2015-11', 'dhaka2016-3',
        'dhaka2016-10', 'dhaka2016-12', 'dhaka2017-1', 'dhaka2017-3',
        'dhaka2017-6', 'dhaka2017-12', 'dhaka2019-3', 'gazipur2018-9',
        'madaripur2019-9', 'munshiganj2018-8', 'narayanganj2019-9',
        'tangail2019-9', 'kushtia2018-11', 'narail2015-10', 'narail2019-9',
        'naogaon2017-7', 'rajshahi2015-8', 'rajshahi2017-5', 'dinajpur2018-2',
        'dinajpur2018-10', 'dinajpur2019-6', 'panchagarh2019-9',
        'rangpur2018-5', 'rangpur2018-9', 'thakurgaon2019-9', 'habiganj2019-9',
        'sunamganj2019-7', 'sylhet2016-9', 'sylhet2018-8'],
       dtype='object', name='locations_month'),
 2: Index(['bhola2019-9', 'patuakhali2019-7', 'bandarban2019-7',
        'brahmanbaria2019-7', 'chittagong2018-11', 'rangamati2019-9',
        'dhaka2015-2', 'dhaka2016-5', 'dhaka2017-8', 'dhaka2017-11',
        'dhaka2019-1', 'faridpur2017-9', 'gopalganj2019-9', 'tangail2017-9',
        'jessore2015-7', 'jessore2016-4', 'mymensingh2017-2', 'sherpur2019-9',
        'rajshahi2016-8', 'rajshahi2017-7', 'dinajpur2017-11', 'dinajpur2018-7',
        'panchagarh2019-7', 'rangpur2019-9'],
       dtype='object', name='locations_month'),
 3: Index(['chandpur2019-9', 'rangamati2019-7', 'dhaka2015-7', 'dhaka2017-10',
        'gopalganj2019-7', 'munshiganj2019-7', 'bagerhat2019-9',
        'jamalpur2019-7'],
       dtype='object', name='locations_month'),
 4: Index(['chandpur2019-7', 'dhaka2017-9', 'dhaka2019-4', 'madaripur2019-7',
        'manikganj2019-7', 'narsingdi2019-7', 'panchagarh2019-8'],
       dtype='object', name='locations_month'),
 5: Index(['feni2019-7', 'dhaka2015-8', 'dhaka2019-2', 'dhaka2019-5',
        'gazipur2019-9', 'kishoreganj2019-7', 'manikganj2019-9',
        'narayanganj2019-7', 'naogaon2019-7', 'sirajganj2019-7',
        'dinajpur2017-10'],
       dtype='object', name='locations_month'),
 6: Index(['pirojpur2019-8', 'lakshmipur2019-7', 'dhaka2016-9', 'dhaka2017-5',
        'dhaka2018-2', 'dhaka2018-12', 'bagerhat2019-7', 'pabna2019-9'],
       dtype='object', name='locations_month'),
 7: Index(['brahmanbaria2019-8', 'chittagong2017-7', 'dhaka2018-6',
        'kishoreganj2019-8', 'narsingdi2017-7', 'tangail2019-7',
        'sylhet2019-9'],
       dtype='object', name='locations_month'),
 8: Index(['rangamati2019-8', 'dhaka2016-8', 'munshiganj2019-8',
        'mymensingh2019-7', 'habiganj2019-8'],
       dtype='object', name='locations_month'),
 9: Index(['dhaka2016-6', 'narsingdi2019-8', 'jamalpur2019-8', 'sunamganj2019-8'], dtype='object', name='locations_month'),
 10: Index(['dhaka2018-3', 'sirajganj2019-9'], dtype='object', name='locations_month'),
 11: Index(['comilla2019-7', 'narayanganj2019-8', 'jessore2019-7', 'sherpur2019-7',
        'rajshahi2019-7'],
       dtype='object', name='locations_month'),
 12: Index(['bandarban2019-8', 'dhaka2017-7', 'faridpur2019-7', 'rangpur2019-7',
        'thakurgaon2019-7'],
       dtype='object', name='locations_month'),
 13: Index(['bhola2019-7', 'manikganj2019-8', 'mymensingh2019-9'], dtype='object', name='locations_month'),
 14: Index(['patuakhali2019-8', 'dhaka2016-7', 'gazipur2019-8'], dtype='object', name='locations_month'),
 15: Index(['sherpur2019-8'], dtype='object', name='locations_month'),
 16: Index(['lakshmipur2019-8', 'noakhali2019-7', 'faridpur2019-9', 'tangail2019-8',
        'narail2019-7', 'naogaon2019-8'],
       dtype='object', name='locations_month'),
 17: Index(['dhaka2018-8', 'satkhira2019-7'], dtype='object', name='locations_month'),
 18: Index(['chittagong2019-9', 'feni2019-8', 'dhaka2015-9'], dtype='object', name='locations_month'),
 19: Index(['gazipur2019-7', 'dinajpur2019-7'], dtype='object', name='locations_month'),
 20: Index(['chandpur2019-8', 'pabna2019-7'], dtype='object', name='locations_month'),
 22: Index(['gopalganj2019-8'], dtype='object', name='locations_month'),
 23: Index(['dhaka2018-10', 'pabna2019-8'], dtype='object', name='locations_month'),
 24: Index(['bhola2019-8', 'kushtia2019-7', 'sirajganj2019-8'], dtype='object', name='locations_month'),
 25: Index(['barisal2019-9'], dtype='object', name='locations_month'),
 26: Index(['dhaka2019-6', 'madaripur2019-8', 'satkhira2019-9'], dtype='object', name='locations_month'),
 27: Index(['dhaka2018-7', 'rajshahi2019-9'], dtype='object', name='locations_month'),
 28: Index(['comilla2019-8', 'thakurgaon2019-8'], dtype='object', name='locations_month'),
 29: Index(['dhaka2015-10', 'bagerhat2019-8'], dtype='object', name='locations_month'),
 30: Index(['chittagong2019-7', 'dhaka2018-9', 'jessore2019-9'], dtype='object', name='locations_month'),
 36: Index(['kushtia2019-9'], dtype='object', name='locations_month'),
 39: Index(['dhaka2018-11'], dtype='object', name='locations_month'),
 44: Index(['sylhet2019-7'], dtype='object', name='locations_month'),
 46: Index(['rajshahi2019-8'], dtype='object', name='locations_month'),
 51: Index(['noakhali2019-8'], dtype='object', name='locations_month'),
 52: Index(['narail2019-8'], dtype='object', name='locations_month'),
 53: Index(['faridpur2019-8', 'jessore2019-8'], dtype='object', name='locations_month'),
 57: Index(['barisal2019-7'], dtype='object', name='locations_month'),
 58: Index(['habiganj2019-7'], dtype='object', name='locations_month'),
 62: Index(['mymensingh2019-8'], dtype='object', name='locations_month'),
 64: Index(['dinajpur2019-8'], dtype='object', name='locations_month'),
 73: Index(['barisal2019-8', 'chittagong2019-8'], dtype='object', name='locations_month'),
 79: Index(['rangpur2019-8'], dtype='object', name='locations_month'),
 81: Index(['kushtia2019-8'], dtype='object', name='locations_month'),
 91: Index(['sylhet2019-8'], dtype='object', name='locations_month'),
 96: Index(['satkhira2019-8'], dtype='object', name='locations_month'),
 131: Index(['dhaka2019-9'], dtype='object', name='locations_month'),
 809: Index(['dhaka2019-7'], dtype='object', name='locations_month'),
 885: Index(['dhaka2019-8'], dtype='object', name='locations_month')}

In [41]:
data.to_excel('data_v6.xlsx')